import * as React from "react"
import { Link } from "gatsby"
import Footer from "../components/footer"
import * as termsStyles from "../styles/terms.module.css"

const TermsPage = () => {
  return (
    <main>
      <p>
        <Link to="/">← Home</Link>
      </p>
      <div>
        <div />
        <div className={termsStyles.termsContent}>
          <h1>Terms and Conditions</h1>

          <p>Thank you for using Mystic Mind, a service of Invictus Technologies L.L.C!</p>
          <p>These Terms of Use apply when you use the Mystic Mind service of Invictus Technologies L.L.C. (“Invictus Technologies”) or its affiliates, data, documentation, and websites (“Services”). The Terms include documentation, guidelines, or policies Invictus Technologies may provide in writing. By using the Services, you agree to these Terms.</p>

          <h2>1. Registration and Access</h2>
          <p>You must be at least 13 years old to use the Services. If you are under 18, you must have your parent or legal guardian’s permission to use the Services. If you use the Services on behalf of another person or entity, you must have the authority to accept the Terms on their behalf. You must provide accurate and complete information to register for an account. You may not make your access credentials or account available to others outside your organization, and you are responsible for all activities that occur using your credentials.</p>

          <h2>2. Usage Requirements</h2>
          <ol type="a">
            <li><p><strong>Use of Services.</strong> You may access, and Invictus Technologies grants you, a non-exclusive right to use the Services in accordance with these Terms. You will comply with these Terms and all applicable laws when using the Services. Invictus Technologies and its affiliates own all rights, title, and interest in and to the Services.</p></li>
            <li><p><strong>Feedback.</strong> Invictus Technologies appreciates feedback, comments, ideas, proposals, and suggestions for improvements. If you provide any of these things, Invictus Technologies may use it without restriction or compensation to you.</p></li>
            <li><p><strong>Restrictions.</strong> You may not (i) use the Services in a way that infringes, misappropriates or violates any person’s rights; (ii) reverse assemble, reverse compile, decompile, translate or otherwise attempt to discover the source code or underlying components of models, algorithms, and systems of the Services (except to the extent such restrictions are contrary to applicable law); (iii) use output from the Services to develop models that compete with Invictus Technologies; (iv) use any automated or programmatic method to extract data or output from the Services, including scraping, web harvesting, or web data extraction; (v) represent that output from the Services was human-generated when it is not or otherwise violate Invictus Technologies’ Usage Policies; or (vii), send us any personal information of children under 13 or the applicable age of digital consent. You will comply with any rate limits and other requirements in Invictus Technologies’ documentation.</p></li>
            <li><p><strong>Third Party Services.</strong> Any third-party software, services, or other products you use in connection with the Services are subject to their own terms, and Invictus Technologies is not responsible for third party products.</p></li>
          </ol>

          <h2>3. Content</h2>
          <ol type="a">
            <li><p><strong>Your Content.</strong> You may provide input to the Services (“Input”), and receive output generated and returned by the Services based on the Input (“Output”). Input and Output are collectively “Content.” As between the parties and to the extent permitted by applicable law, you own all Input. Subject to your compliance with these Terms, Invictus Technologies hereby assigns to you all its right, title and interest in and to Output. This means you can use Content for any purpose, including commercial purposes such as sale or publication, if you comply with these Terms. Invictus Technologies may use Content to provide and maintain the Services, comply with applicable law, and enforce Invictus Technologies’ policies. You are responsible for Content, including for ensuring that it does not violate any applicable law or these Terms.</p></li>
            <li><p><strong>Similarity of Content.</strong> Due to the nature of machine learning, Output may not be unique across users and the Services may generate the same or similar output for Mystic Mind or a third party. For example, you may provide input to a model such as “What color is the sky?” and receive output such as “The sky is blue.” Other users may also ask similar questions and receive the same response. Responses that are requested by and generated for other users are not considered your Content.</p></li>
            <li><p><strong>Accuracy.</strong> Artificial intelligence and machine learning are rapidly evolving fields of study. Invictus Technologies is constantly working to improve the Services to make them more accurate, reliable, safe and beneficial. Given the probabilistic nature of machine learning, use of the Services may in some situations result in incorrect Output that does not accurately reflect real people, places, or facts. You should evaluate the accuracy of any Output as appropriate for your use case, including by using human review of the Output.</p></li>
          </ol>

          <h2>4. Fees and Payments</h2>
          <ol type="a">
            <li><p><strong>Fees and Billing.</strong> You will pay all fees charged to your account (“Fees”) according to the prices and terms on the applicable pricing page, or as otherwise agreed between us in writing. Invictus Technologies has the right to correct pricing errors or mistakes even if it has already issued an invoice or received payment. You will provide complete and accurate billing information including a valid and authorized payment method. Invictus Technologies will charge your payment method on an agreed-upon periodic basis but may reasonably change the date on which the charge is posted. You authorize Invictus Technologies and its affiliates and third-party payment processor(s), to charge your payment method for the Fees. If your payment cannot be completed, Invictus Technologies will provide you written notice and may suspend access to the Services until payment is received. Fees are payable in U.S. dollars and are due upon invoice issuance. Payments are nonrefundable except as provided in this Agreement.</p></li>
            <li><p><strong>Price Changes.</strong> Invictus Technologies may change its prices by posting notice to your account and/or to the website or Discord channel of the Services. Price increases will be effective 14 days after they are posted, except for increases made for legal reasons, which will be effective immediately. Any price changes will apply to the Fees charged to your account immediately after the effective date of the changes.</p></li>
          </ol>

          <h2>5. Term and Termination</h2>
          <ol type="a">
            <li><p><strong>Termination; Suspension.</strong> These Terms take effect when you first use the Services and remain in effect until terminated. You may terminate these Terms at any time for any reason by discontinuing the use of the Services and Content. Invictus Technologies may terminate these Terms for any reason by providing you at least 30 days’ advance notice. Invictus Technologies may terminate these Terms immediately upon notice to you if you materially breach Sections 2 (Usage Requirements), 5 (Confidentiality, Security and Data Protection), 8 (Dispute Resolution) or 9 (General Terms), if there are changes in relationships with third party technology providers outside of Invictus Technologies’ control, or to comply with law or government requests. Invictus Technologies may suspend your access to the Services if you do not comply with these Terms, if your use poses a security risk to Invictus Technologies or any third party, or if Invictus Technologies suspects that your use is fraudulent or could subject it or any third party to liability.</p></li>
            <li><p><strong>Effect on Termination.</strong> Upon termination, you will stop using the Services and you will promptly return or, if instructed by Invictus Technologies, destroy any Confidential Information. The sections of these Terms which by their nature should survive termination or expiration should survive, including but not limited to Sections 3 and 5-9.</p></li>
          </ol>

          <h2>6. Indemnification; Disclaimer of Warranties; Limitations on Liability</h2>
          <ol type="a">
            <li><p><strong>Indemnity.</strong> You will defend, indemnify, and hold harmless Invictus Technologies, its affiliates, and its personnel, from and against any claims, losses, and expenses (including attorneys’ fees) arising from or relating to your use of the Services, including your Content, products or services you develop or offer in connection with the Services, and your breach of these Terms or violation of applicable law.</p></li>
            <li><p><strong>Disclaimer.</strong> THE SERVICES ARE PROVIDED “AS IS.” EXCEPT TO THE EXTENT PROHIBITED BY LAW, INVICTUS TECHNOLOGIES AND ITS AFFILIATES AND LICENSORS MAKE NO WARRANTIES (EXPRESS, IMPLIED, STATUTORY OR OTHERWISE) WITH RESPECT TO THE SERVICES, AND DISCLAIM ALL WARRANTIES INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, SATISFACTORY QUALITY, NON-INFRINGEMENT, AND QUIET ENJOYMENT, AND ANY WARRANTIES ARISING OUT OF ANY COURSE OF DEALING OR TRADE USAGE. INVICTUS TECHNOLOGIES DOES NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ACCURATE OR ERROR FREE, OR THAT ANY CONTENT WILL BE SECURE OR NOT LOST OR ALTERED.</p></li>
            <li><p><strong>Limitations of Liability.</strong>  NEITHER INVICTUS TECHNOLOGIES NOR ANY OF ITS AFFILIATES OR LICENSORS WILL BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, OR DATA OR OTHER LOSSES, EVEN IF INVICTUS TECHNOLOGIES HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. INVICTUS TECHNOLOGIES’ AGGREGATE LIABILITY UNDER THESE TERMS SHALL NOT EXCEED ​​THE GREATER OF THE AMOUNT YOU PAID FOR THE SERVICE THAT GAVE RISE TO THE CLAIM DURING THE 12 MONTHS BEFORE THE LIABILITY AROSE OR ONE HUNDRED DOLLARS ($100). THE LIMITATIONS IN THIS SECTION APPLY ONLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW.</p></li>
          </ol>

          <h2>8. Dispute Resolution</h2>
          <p>YOU AGREE TO THE FOLLOWING MANDATORY ARBITRATION AND CLASS ACTION WAIVER PROVISIONS:</p>

          <ol type="a">
            <li><p><strong>MANDATORY ARBITRATION.</strong> You and Invictus Technologies agree to resolve any past or present claims relating to these Terms or the Services through final and binding arbitration, except that you have the right to opt out of these arbitration terms, and future changes to these arbitration terms, by sending written notice to InvictusMystic@protonmail.com containing your name, email, and username.</p></li>
            <li><p><strong>Informal Dispute Resolution.</strong> Invictus Technologies would like to understand and try to address your concerns prior to formal legal action. Before filing a claim against Invictus Technologies, you agree to try to resolve the dispute informally by sending us notice at InvictusMystic@protonmail.com  of your name, a description of the dispute, and the relief you seek. If Invictus Technologies is unable to resolve a dispute within 60 days, you may bring a formal proceeding. Any statute of limitations will be tolled during the 60-day resolution process. If you reside in the EU, the European Commission provides for an online dispute resolution platform, which you can access at https://ec.europa.eu/consumers/odr.</p></li>
            <li><p><strong>Arbitration Forum.</strong> Either party may commence binding arbitration through an alternative dispute resolution provider chosen by Invictus Technologies. The parties will pay equal shares of the arbitration fees. If the arbitrator finds that you cannot afford to pay the arbitration fees and cannot obtain a waiver, Invictus Technologies will pay them for you. Invictus Technologies will not seek its attorneys’ fees and costs in arbitration unless the arbitrator determines that your claim is frivolous.</p></li>
            <li><p><strong>Arbitration Procedures.</strong> The arbitration will be conducted by telephone, based on written submissions, video conference, or in person at a mutually agreed location. The arbitration will be conducted by a sole arbitrator under its then-prevailing rules. All issues are for the arbitrator to decide, except a Colorado court has the authority to determine (i) the scope, enforceability, and arbitrability of this Section 8, including the mass filing procedures below, and (ii) whether you have complied with the pre-arbitration requirements in this section. The amount of any settlement offer will not be disclosed to the arbitrator by either party until after the arbitrator determines the final award, if any.</p></li>
            <li><p><strong>Exceptions.</strong> This arbitration section does not require arbitration of the following claims: (i) individual claims brought in small claims court; and (ii) injunctive or other equitable relief to stop unauthorized use or abuse of the Services or intellectual property infringement.</p></li>
            <li><p><strong>NO CLASS ACTIONS.</strong> Disputes must be brought on an individual basis only and may not be brought as a plaintiff or class member in any purported class, consolidated, or representative proceeding. Class arbitrations, class actions, private attorney general actions, and consolidation with other arbitrations are not allowed. If for any reason a dispute proceeds in court rather than through arbitration, each party knowingly and irrevocably waives any right to trial by jury in any action, proceeding, or counterclaim. This does not prevent either party from participating in a class-wide settlement of claims.</p></li>
            <li><p><strong>Mass Filings.</strong> If, at any time, 30 or more similar demands for arbitration are asserted against Invictus Technologies or related parties by the same or coordinated counsel or entities (“Mass Filing”), an alternative dispute resolution provider chosen by Invictus Technologies L.L.C. will randomly assign sequential numbers to each of the Mass Filings. Claims numbered 1-10 will be the “Initial Test Cases” and will proceed to arbitration first. The arbitrators will render a final award for the Initial Test Cases within 120 days of the initial pre-hearing conference, unless the claims are resolved in advance, or the parties agree to extend the deadline. The parties will then have 90 days (the “Mediation Period”) to resolve the remaining cases in mediation based on the awards from the Initial Test Cases. If the parties are unable to resolve the outstanding claims during this time, the parties may choose to opt out of the arbitration process and proceed in court by providing written notice to the other party within 60 days after the Mediation Period. Otherwise, the remaining cases will be arbitrated in their assigned order. Any statute of limitations will be tolled from the time the Initial Test Cases are chosen until your case is chosen as described above.</p></li>
            <li><p><strong>Severability.</strong> If any part of this Section 8 is found to be illegal or unenforceable, the remainder will remain in effect, except that if a finding of partial illegality or unenforceability would allow Mass Filing or class or representative arbitration, this Section 8 will be unenforceable in its entirety. Nothing in this section will be deemed to waive or otherwise limit the right to seek public injunctive relief or any other non-waivable right, pending a ruling on the substance of such claim from the arbitrator.</p></li>
          </ol>

          <h2>9. General Terms</h2>
          <ol type="a">
            <li><p><strong>Relationship of the Parties.</strong> These Terms do not create a partnership, joint venture, or agency relationship between you and Invictus Technologies or any of Invictus Technologies’ affiliates. Invictus Technologies and you are independent contractors and neither party will have the power to bind the other or to incur obligations on the other’s behalf without the other party’s prior written consent.</p></li>
            <li><p><strong>Use of Brands.</strong> You may not use Invictus Technologies’ or any of its affiliates’ names, logos, or trademarks, without prior written consent from the Chief Executive Officer of Invictus Technologies.</p></li>
            <li><p><strong>U.S. Federal Agency Entities.</strong> The Services were developed solely at private expense and are commercial computer software and related documentation within the meaning of the applicable U.S. Federal Acquisition Regulation and agency supplements thereto.</p></li>
            <li><p><strong>Copyright Complaints.</strong> If you believe that your intellectual property rights have been infringed, please send notice to this email address InvictusMystic@protonmail.com. Invictus Technologies may delete or disable content alleged to be infringing and may terminate accounts of repeat infringers.</p></li>
            <li><p><strong>Assignment and Delegation.</strong> You may not assign or delegate any rights or obligations under these Terms, including in connection with a change of control. Any purported assignment and delegation shall be null and void. Invictus Technologies may assign these Terms in connection with a merger, acquisition or sale of all or substantially all of its assets, or to any affiliate or as part of a corporate reorganization.</p></li>
            <li><p><strong>Modifications.</strong> Invictus Technologies may amend these Terms from time to time by posting a revised version on the website, or if an update materially adversely affects your rights or obligations under these Terms, Invictus Technologies will provide notice to you either by emailing the email associated with your account or providing an in-product notification. Those changes will become effective no sooner than 30 days after Invictus Technologies notifies you. All other changes will be effective immediately. Your continued use of the Services after any change means you agree to such change.</p></li>
            <li><p><strong>Waiver and Severability.</strong> If you do not comply with these Terms, and Invictus Technologies does not take action right away, this does not mean Invictus Technologies is giving up any of its rights. Except as provided in Section 8, if any part of these Terms is determined to be invalid or unenforceable by a court of competent jurisdiction, that term will be enforced to the maximum extent permissible, and it will not affect the enforceability of any other terms.</p></li>
            <li><p><strong>Export Controls.</strong> The Services may not be used in or for the benefit of, exported, or re-exported (a) into any U.S. embargoed countries (collectively, the “Embargoed Countries”) or (b) to anyone on the U.S. Treasury Department’s list of Specially Designated Nationals, any other restricted party lists (existing now or in the future) identified by the Office of Foreign Asset Control, or the U.S. Department of Commerce Denied Persons List or Entity List, or any other restricted party lists (collectively, “Restricted Party Lists”). You represent and warrant that you are not located in any Embargoed Countries and not on any such restricted party lists. You must comply with all applicable laws related to Embargoed Countries or Restricted Party Lists, including any requirements or obligations to know your end users directly.</p></li>
            <li><p><strong>Equitable Remedies.</strong> You acknowledge that if you violate or breach these Terms, it may cause irreparable harm to Invictus Technologies and its affiliates, and Invictus Technologies shall have the right to seek injunctive relief against you in addition to any other legal remedies.</p></li>
            <li><p><strong>Entire Agreement.</strong> These Terms and any policies incorporated in these Terms contain the entire agreement between you and Invictus Technologies regarding the use of the Services and, other than any Service specific terms of use or any applicable enterprise agreements, supersedes any prior or contemporaneous agreements, communications, or understandings between you and Invictus Technologies on that subject.</p></li>
          </ol>

        </div>
        <div />
      </div>
      <p>
        <Link to="/">← Home</Link>
      </p>
      <br />
      <Footer />
    </main>
  )
}

export default TermsPage

export const Head = () => <title>Terms and Conditions</title>